export default [
  {
    id: 0,
    name: "Pussy Meme",
    sound: new Audio("https://www.myinstants.com/media/sounds/pussy-sound-effect_1.mp3"),
    sfw: false,
  },
  {
    id: 1,
    name: "Airhorn",
    sound: new Audio("https://www.myinstants.com/media/sounds/mlg-airhorn.mp3"),
    sfw: true,
  },
  {
    id: 2,
    name: "Senpai Obama",
    sound: new Audio("https://www.myinstants.com/media/sounds/senpai-cum-in-my-ass-and-call-me-obama-audio-clip.mp3"),
    sfw: false,
  },
  {
    id: 3,
    name: "Nut",
    sound: new Audio("https://www.myinstants.com/media/sounds/nut_ZKo5FA9.mp3"),
    sfw: false,
  },
  {
    id: 4,
    name: "Ear Rape",
    sound: new Audio("https://www.myinstants.com/media/sounds/ear-rape-moaning-girl-troll-sound-crappy-long-edition-loudtronix-hq.mp3"),
    sfw: false,
  },
  {
    id: 5,
    name: "Shut up",
    sound: new Audio("https://www.myinstants.com/media/sounds/shutup.swf.mp3"),
    sfw: true,
  },
  {
    id: 6,
    name: "Discord Notification",
    sound: new Audio("https://www.myinstants.com/media/sounds/discord-notification.mp3"),
    sfw: true,
  },
  {
    id: 7,
    name: "Step Bro",
    sound: new Audio("https://www.myinstants.com/media/sounds/what-are-you-doing-step-bro-tik-tok-meme.mp3"),
    sfw: false,
  },
  {
    id: 8,
    name: "Wow",
    sound: new Audio("https://www.myinstants.com/media/sounds/anime-wow-sound-effect.mp3"),
    sfw: true,
  },
  {
    id: 9,
    name: "Law and Order",
    sound: new Audio("https://www.myinstants.com/media/sounds/dun_dun_1.mp3"),
    sfw: true,
  },
  {
    id: 10,
    name: "Minecraft Hurt",
    sound: new Audio("https://www.myinstants.com/media/sounds/classic_hurt.mp3"),
    sfw: true,
  },
  {
    id: 11,
    name: "Fuck Off",
    sound: new Audio("https://www.myinstants.com/media/sounds/fuckoff.mp3"),
    sfw: false,
  },
  {
    id: 12,
    name: "Fap",
    sound: new Audio("https://www.myinstants.com/media/sounds/savage-fap.mp3"),
    sfw: false,
  },
  {
    id: 13,
    name: "Leroy Jenkins",
    sound: new Audio("https://www.myinstants.com/media/sounds/leroy.swf.mp3"),
    sfw: true,
  },
  {
    id: 14,
    name: "FBI",
    sound: new Audio("https://www.myinstants.com/media/sounds/fbi-open-up-sfx.mp3"),
    sfw: true,
  },
  {
    id: 15,
    name: "Fuck this shit",
    sound: new Audio("https://www.myinstants.com/media/sounds/fuck-this-shit-im-out.mp3"),
    sfw: false,
  },
  {
    id: 16,
    name: "Discord Call",
    sound: new Audio("https://www.myinstants.com/media/sounds/discord-call-sound.mp3"),
    sfw: true,
  },
  {
    id: 17,
    name: "Discord Join",
    sound: new Audio("https://www.myinstants.com/media/sounds/discord-sounds.mp3"),
    sfw: true,
  },
];
